language: android

notifications:
  email: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-19.0.3
    - android-18
    - sysimg-18
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

before_install:
  # environment info
  - gradle -v
  - uname -a
  - cat /home/travis/build.sh
