language: android

notifications:
  email: false

android:
  components:
    - tools
    - build-tools-19.0.3
    - android-18
    - sysimg-18
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

