language: android
jdk: oraclejdk7

notifications:
  email: false

android:
  components:
    - build-tools-21.1.2
    - android-19
    - sys-img-armeabi-v7a-android-19
    - add-on
    - extra
  licenses:
    - 'android-sdk-license-.+'

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

